// ============================================================
// Glossário de termos financeiros para tooltips educacionais.
// Barrel file — re-exports from glossary-dashboard and glossary-features.
// ============================================================

export type { EntradaGlossario } from "./glossary-dashboard";

// Dashboard components
export {
  GLOSSARY_PATRIMONIO_TOTAL,
  GLOSSARY_VARIACAO_PATRIMONIAL,
  GLOSSARY_GANHOS_NO_MES,
  GLOSSARY_RENTABILIDADE_MENSAL,
  GLOSSARY_RENTABILIDADE_ANUAL,
  GLOSSARY_DESDE_INICIO,
  GLOSSARY_EVOLUCAO_PATRIMONIAL,
  GLOSSARY_TOTAL_APORTADO,
  GLOSSARY_RENDIMENTOS,
  GLOSSARY_ALOCACAO_POR_ESTRATEGIA,
  GLOSSARY_ESTRATEGIAS,
  GLOSSARY_CARTEIRA_VS_BENCHMARKS,
  GLOSSARY_CDI,
  GLOSSARY_IBOVESPA,
  GLOSSARY_IPCA,
  GLOSSARY_MELHORES_PERFORMERS,
  GLOSSARY_PIORES_PERFORMERS,
  GLOSSARY_ATIVO,
  GLOSSARY_SALDO,
  GLOSSARY_RENTABILIDADE_MES,
  GLOSSARY_PARTICIPACAO,
  GLOSSARY_GANHOS_POR_ESTRATEGIA,
  GLOSSARY_PERIODO_NO_MES,
  GLOSSARY_PERIODO_NO_ANO,
  GLOSSARY_PERIODO_12_MESES,
  GLOSSARY_PERIODO_DESDE_INICIO,
  GLOSSARY_EVENTO_FINANCEIRO,
  GLOSSARY_TIPOS_EVENTO,
  GLOSSARY_RETORNOS_MENSAIS,
  GLOSSARY_PERCENTUAL_CDI,
} from "./glossary-dashboard";

// Feature components (risk, liquidity, positions, categories, movements, trends, etc.)
export {
  GLOSSARY_RISCO_CONSISTENCIA,
  GLOSSARY_VOLATILIDADE,
  GLOSSARY_LIQUIDEZ,
  GLOSSARY_TODAS_POSICOES,
  GLOSSARY_RENTABILIDADE_12M,
  GLOSSARY_RENTABILIDADE_DESDE_INICIO_ATIVO,
  GLOSSARY_RENTABILIDADE_POR_CATEGORIA,
  GLOSSARY_MOVIMENTACOES,
  GLOSSARY_EVOLUCAO_ALOCACAO,
  GLOSSARY_COMPARACAO_PERIODOS,
  GLOSSARY_IBOVESPA_INDICE,
  GLOSSARY_SELIC_META,
  GLOSSARY_IPCA_INDICE,
  GLOSSARY_CDI_TAXA,
  GLOSSARY_IGPM,
  GLOSSARY_DOLAR,
  GLOSSARY_VOLUME_NEGOCIACAO,
  GLOSSARY_HEATMAP_SETORES,
  GLOSSARY_MAIORES_ALTAS,
  GLOSSARY_MAIORES_BAIXAS,
  GLOSSARY_MAIS_NEGOCIADAS,
  GLOSSARY_FUNDOS_EM_ALTA,
} from "./glossary-features";
